=== deppimaracanau/html/deppibkp/paginas/Programas/DbVisualizer/resources/profiles/dbvis-defs.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   Copyright (c) DbVis Software AB. All Rights Reserved.
-->

<!-- =================================================================== -->
<!-- DTD for database profile XML documents in DbVisualizer -->
<!-- =================================================================== -->

<!-- DatabaseProfile -->

<!ELEMENT DatabaseProfile (InitCommands | Commands | ObjectsActionDef | ObjectsTreeDef | ObjectsViewDef)*>
<!ATTLIST DatabaseProfile desc CDATA #IMPLIED
                          version CDATA #IMPLIED
                          minver CDATA #IMPLIED
                          date CDATA #IMPLIED
                          extends CDATA #IMPLIED>

<!-- If, ElseIf, Else -->
<!ELEMENT If (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | ProcessDataSet | ProcessSQLWarning | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg | Labels | Values | Default)*>
<!ATTLIST If test CDATA #REQUIRED
             context (load | runtime) #IMPLIED
             action (drop) #IMPLIED>

<!ELEMENT ElseIf (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | ProcessDataSet | ProcessSQLWarning | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg | Labels | Values | Default)*>
<!ATTLIST ElseIf test CDATA #REQUIRED
                 context (load | runtime) #IMPLIED
                 action (drop) #IMPLIED>

<!ELEMENT Else (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | ProcessDataSet | ProcessSQLWarning | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg | Labels | Values | Default)*>
<!ATTLIST Else action (drop) #IMPLIED>

<!-- Commands -->
<!ELEMENT InitCommands (OnError | Command | If | ElseIf | Else)*>
<!ATTLIST InitCommands extends (true | false) #REQUIRED>

<!ELEMENT Commands (OnError | Command | If | ElseIf | Else)*>
<!ATTLIST Commands extends (true | false) #REQUIRED>

<!ELEMENT Command (Output | Input | ProcessDataSet | ProcessSQLWarning | SQL | Filter | OnError | If | ElseIf | Else)*>
<!ATTLIST Command id ID #IMPLIED
                  idref IDREF #IMPLIED
                  method (jdbc | dynamic | runBeforeConditionsEval) #IMPLIED
                  exectype (script | asis | explain) #IMPLIED
                  processmarkers (true | withdriver) #IMPLIED
                  autocommit (false) #IMPLIED
                  whensuccess (commit | rollback | ask) #IMPLIED
                  whenerror (commit | rollback | ask | ignore) #IMPLIED>

<!-- OnError -->
<!ELEMENT OnError (Message | If | ElseIf | Else)*>

<!-- Filter -->
<!ELEMENT Filter (If | ElseIf | Else)*>
<!ATTLIST Filter index CDATA #REQUIRED
                 label CDATA #REQUIRED>

<!-- ObjectsActionDef -->

<!ELEMENT ObjectsActionDef (ActionGroup | If | ElseIf | Else)*>
<!ATTLIST ObjectsActionDef extends (true | false) #REQUIRED>

<!-- ObjectsTreeDef -->

<!ELEMENT ObjectsTreeDef (DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST ObjectsTreeDef extends (true | false) #REQUIRED>

<!ELEMENT DataNode (SetVar | Command | DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST DataNode type CDATA #REQUIRED
                   actiontype CDATA #IMPLIED
                   label CDATA #REQUIRED
                   label1 CDATA #IMPLIED
                   icon CDATA #IMPLIED
                   tip CDATA #IMPLIED
                   stop-label-not-equal CDATA #IMPLIED
                   drop-label-not-equal CDATA #IMPLIED
                   is-empty-output (continue | stop) #IMPLIED
                   is-catalog-database CDATA #IMPLIED
                   isLeaf CDATA #IMPLIED
                   warnstate CDATA #IMPLIED
                   errorstate CDATA #IMPLIED
                   action (drop) #IMPLIED
                   order-before CDATA #IMPLIED
                   order-after CDATA #IMPLIED>

<!ELEMENT SetVar (#PCDATA | If | ElseIf | Else)*>
<!ATTLIST SetVar name CDATA #REQUIRED
                 value CDATA #IMPLIED
                 action (show | hide | drop | runwheninit) #IMPLIED>

<!ELEMENT GroupNode (SetVar | DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST GroupNode type CDATA #REQUIRED
                    label CDATA #REQUIRED
                    label1 CDATA #IMPLIED
                    icon CDATA #IMPLIED
                    drop-label-not-equal CDATA #IMPLIED
                    isLeaf CDATA #IMPLIED
                    action (drop) #IMPLIED
                    order-before CDATA #IMPLIED
                    order-after CDATA #IMPLIED>

<!-- ObjectsViewDef -->

<!ELEMENT ObjectsViewDef (ObjectView | If | ElseIf | Else)*>
<!ATTLIST ObjectsViewDef extends (true | false) #REQUIRED>

<!ELEMENT ObjectView (DataView | If | ElseIf | Else)*>
<!ATTLIST ObjectView type CDATA #REQUIRED
                     action (drop) #IMPLIED
                     order-before CDATA #IMPLIED
                     order-after CDATA #IMPLIED>

<!ELEMENT DataView (DataView | Input | Action | Command | Message | If | ElseIf | Else)*>
<!ATTLIST DataView id ID #REQUIRED
                   label CDATA #IMPLIED
                   icon CDATA #IMPLIED
                   viewer (grid | text | form | node-form | table-refs | tables-refs | table-data | table-rowcount | message | navigator | ProcedureViewer | ddl) #IMPLIED
                   drop-label-not-equal CDATA #IMPLIED
                   class CDATA #IMPLIED
                   classargs CDATA #IMPLIED
                   action (drop) #IMPLIED
                   doclink CDATA #IMPLIED
                   order-before CDATA #IMPLIED
                   order-after CDATA #IMPLIED>

<!-- Common elements -->

<!ELEMENT Message (#PCDATA | If | ElseIf | Else)*>
<!ATTLIST Message type (info | warning | error) #IMPLIED>
<!ELEMENT Confirm (#PCDATA | If | ElseIf | Else)*>
<!ELEMENT Result (#PCDATA | If | ElseIf | Else)*>
<!ELEMENT Values (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Values column CDATA #IMPLIED>
<!ELEMENT Labels (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Labels column CDATA #IMPLIED>
<!ELEMENT Default (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Default column CDATA #IMPLIED>

<!ELEMENT ActionGroup (ActionGroup | Action | Separator | If | ElseIf | Else)*>
<!ATTLIST ActionGroup type CDATA #IMPLIED
                      label CDATA #IMPLIED
                      action (drop) #IMPLIED
                      order-before CDATA #IMPLIED
                      order-after CDATA #IMPLIED>


<!ELEMENT Separator (#PCDATA)*>

<!ELEMENT Action (Command | Confirm | SQL | Result | Input | SetVar | Message | If | ElseIf | Else)*>
<!ATTLIST Action id ID #REQUIRED
                 icon CDATA #IMPLIED
                 label CDATA #IMPLIED
                 reload (true | false) #IMPLIED
                 resetcatalogs (true | false) #IMPLIED
                 resetschemas (true | false) #IMPLIED
                 supportsmultipleobjects (true | false) #IMPLIED
                 class CDATA #IMPLIED
                 classargs CDATA #IMPLIED
                 mode (script | script-immediate) #IMPLIED
                 resultaction (mergeasscript | mergeastext) #IMPLIED
                 resulttarget (editor) #IMPLIED
                 doclink CDATA #IMPLIED
                 hideif CDATA #IMPLIED
                 action (drop) #IMPLIED
                 order-before CDATA #IMPLIED
                 order-after CDATA #IMPLIED>

<!ELEMENT Arg (#PCDATA | If | ElseIf | Else)*>
<!ATTLIST Arg name CDATA #REQUIRED
              value CDATA #REQUIRED>

<!ELEMENT SQL (#PCDATA | If | ElseIf | Else)*>

<!ELEMENT Input (Values | Labels | Default | Input | Arg | If | ElseIf | Else | SetVar)*>
<!ATTLIST Input label CDATA #IMPLIED
                name CDATA #IMPLIED
                value CDATA #IMPLIED
                tip CDATA #IMPLIED
                editable (true | false) #IMPLIED
                linebreak (true | false) #IMPLIED
                style (list | radio | text | check | check-list | password | number | text-editor | wrapped-text-editor | grid | separator | label | note) #IMPLIED
                hideif CDATA #IMPLIED
                runsetdefaultwhenvaluechanged CDATA #IMPLIED>

<!ELEMENT Output (If | ElseIf | Else)*>
<!ATTLIST Output index CDATA #REQUIRED
                 name CDATA #REQUIRED>

<!ELEMENT ProcessDataSet (If | ElseIf | Else)*>
<!ATTLIST ProcessDataSet
                 action (renamecolumn | dropcolumn | dropidenticalcolumns | addcolumn | sortcolumn | distinct | removeisnullrows | convertnullvalues | removerowsifequalto | trimcolumn | printdataset) #REQUIRED
                 index CDATA #IMPLIED
                 name CDATA #IMPLIED
                 value CDATA #IMPLIED>

<!ELEMENT ProcessSQLWarning (If | ElseIf | Else)*>
<!ATTLIST ProcessSQLWarning
                 action (converttodataset) #REQUIRED>

=== deppimaracanau/html/DEPPI/paginas/Programas/DbVisualizer/resources/profiles/h2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DatabaseProfile SYSTEM "dbvis-defs.dtd">

<!--
   Copyright (c) DbVis Software AB. All Rights Reserved.
-->

<DatabaseProfile
        desc="Profile for H2"
        minver="9.5"
        extends="generic">

   <Commands extends="true">

      <Command id="h2.getIndexes">
         <SQL>
            <![CDATA[
SELECT
    *
FROM
    INFORMATION_SCHEMA.INDEXES
WHERE
    TABLE_SCHEMA = '${schema}'
    AND TABLE_NAME LIKE '${tableNamePattern}'
    AND NOT IS_GENERATED
ORDER BY INDEX_NAME
            ]]>
         </SQL>
      </Command>

      <Command id="h2.getSequences">
         <SQL>
            <![CDATA[
SELECT
    *
FROM
    INFORMATION_SCHEMA.SEQUENCES
WHERE
    SEQUENCE_SCHEMA = '${schema}'
    AND SEQUENCE_NAME LIKE '${sequenceName}'
ORDER BY SEQUENCE_NAME
            ]]>
         </SQL>
      </Command>

      <Command id="h2.getTriggers">
         <SQL>
            <![CDATA[
select *,
concat('create trigger ', TRIGGER_SCHEMA, '.', TRIGGER_NAME, 
case when BEFORE = TRUE then ' BEFORE' else ' AFTER' end, ' ', TRIGGER_TYPE,' on ', 
TRIGGER_SCHEMA, '.', TABLE_NAME, char(10),
' for each row CALL "', JAVA_CLASS,'"') 
from information_schema.TRIGGERS
where table_schema = '${schema}'
and trigger_name like '${name}'
and TABLE_NAME like '${table_name}'
order by TRIGGER_NAME;
            ]]>
         </SQL>
      </Command>

      <!-- h2.getFunctions -->
      <Command id="h2.getFunctions">
         <SQL>
            <![CDATA[
select * 
from information_schema.FUNCTION_ALIASES
where ALIAS_SCHEMA = '${schema}'
and ALIAS_NAME like '${name}'
order by ALIAS_NAME;
            ]]>
         </SQL>
      </Command>
   </Commands>

   <!-- =================================================================== -->
   <!-- Definition of the object actions that are used by the tree and views -->
   <!-- =================================================================== -->

   <ObjectsActionDef extends="false">

      <ActionGroup type="Schemas">
         <Action id="h2-schemas-create" label="Create Schema" reload="true"
                 resetschemas="true" icon="add">
            <Input label="Schema Name" name="schemaName" style="text"/>
            <Command>
               <SQL><![CDATA[create schema ${QB}${schemaName}${QE}]]></SQL>
            </Command>
            <Result>
               Schema ${schemaName} created!
            </Result>
         </Action>
      </ActionGroup>

      <ActionGroup type="Schema">
         <Action id="h2-schema-drop" label="Drop Schema" reload="true"
                 resetschemas="true" icon="remove">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Command>
               <SQL><![CDATA[drop schema "${schema}"]]></SQL>
            </Command>
            <Confirm>
               Really drop schema ${schema}?
            </Confirm>
            <Result>
               Schema ${schema} has been dropped!
            </Result>
         </Action>
         <Action id="h2-schema-export" label="Export Schema"
                 icon="export" reload="false"
                 class="schemaExport"
                 doclink="http://www.dbvis.com/doclink/export-schema"/>
      </ActionGroup>

      <ActionGroup type="Tables">
         <Action id="h2-tables-create-table" label="Create Table"
                 icon="add" reload="true"
                 class="tableCreateOrAlter"
                 classargs="create"
                 doclink="http://www.dbvis.com/doclink/create-table"/>

         <Action id="h2-new-table-import-data" label="Import Table Data" icon="import"
                 class="tableDataImport"
                 doclink="http://www.dbvis.com/doclink/import-table"/>

      </ActionGroup>

      <ActionGroup type="Table">
         <Action id="h2-tables-alter-table" label="Alter Table"
                 icon="edit" reload="true"
                 class="tableCreateOrAlter"
                 classargs="alter"
                 doclink="http://www.dbvis.com/doclink/alter-table"/>

         <Action id="h2-table-rename" label="Rename Table" reload="true" icon="rename">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Input label="Table" style="text" editable="false">
               <Default>${objectname}</Default>
            </Input>
            <Input label="New Table Name" name="newTable" style="text"/>
            <Command>
               <SQL>
                  <![CDATA[alter table "${schema}"."${objectname}" rename to ${QB}${newTable}${QE}]]></SQL>
            </Command>
            <Confirm>
               Confirm rename of ${schema}.${objectname} to ${newTable}?
            </Confirm>
            <Result>
               Table ${schema}.${objectname} renamed to ${newTable}!
            </Result>
         </Action>

         <Action id="h2-table-clear" label="Empty Table" reload="true">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Input label="Table" style="text" editable="false">
               <Default>${objectname}</Default>
            </Input>

            <Command>
               <SQL><![CDATA[delete from "${schema}"."${objectname}"]]></SQL>
            </Command>
            <Confirm>
               Really remove all rows in table ${schema}.${objectname}?
            </Confirm>
            <Result>
               All rows in table ${schema}.${objectname} has been removed!
            </Result>
         </Action>

         <Action id="h2-table-drop" label="Drop Table" reload="true" icon="remove">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Input label="Table" style="text" editable="false">
               <Default>${objectname}</Default>
            </Input>
            <Input label="Drop Dependent Object(s)" name="cascade" style="check"
                   tip="Automatically drop objects that depend on the table (such as views)">
               <Values>cascade</Values>
            </Input>

            <Command>
               <SQL>
                  <![CDATA[drop table "${schema}"."${objectname}" ${cascade}]]></SQL>
            </Command>
            <Confirm>
               Really drop table ${schema}.${objectname}?
            </Confirm>
            <Result>
               Table ${schema}.${objectname} has been dropped!
            </Result>
         </Action>

         <Action id="h2-table-import-data" label="Import Table Data" icon="import"
                 class="tableDataImport"
                 doclink="http://www.dbvis.com/doclink/import-table"/>

         <Action id="h2-table-export" label="Export Table" icon="export"
                 class="tableExport"
                 doclink="http://www.dbvis.com/doclink/export-table"/>

         <Separator/>

         <Action id="h2-table-create-index" label="Create Index" reload="true">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Input label="Table" style="text" editable="false">
               <Default>${objectname}</Default>
            </Input>
            <Input label="Index Name" name="indexname" style="text"/>
            <Input name="type" label="Type" style="radio">
               <Labels>Non-unique|Unique|Primary Key</Labels>
               <Values>|UNIQUE|PRIMARY KEY</Values>
               <Default>UNIQUE</Default>
            </Input>

            <Input label="Columns" style="separator"/>

            <Input name="columns" style="grid">
               <Arg name="output" value='"${columnname}"${_sortorder}'/>
               <Arg name="newline" value=", "/>

               <Input name="columnname" label="Column Name" style="list">
                  <Values column="4">
                     <Command idref="getColumnNamesFor">
                        <Input name="table_catalog" value="${catalog}"/>
                        <Input name="table_schema" value="${schema}"/>
                        <Input name="table_name" value="${objectname}"/>
                     </Command>
                  </Values>
                  <Default>${0}</Default>
               </Input>
               <Input name="sortorder" label="Sort Order" style="radio">
                  <Labels>ASC|DESC|Default</Labels>
                  <Values>ASC|DESC|</Values>
                  <Default>ASC</Default>
               </Input>
               <SetVar name="_sortorder" value='#sortorder.equals("") ? "" : " " + #sortorder'/>
            </Input>

            <SetVar name="_type" value='#type.equals("") ? "" : " " + #type'/>
            <SetVar name="_columns" value='#columns.trim().equals("") ? "" : "(" + #columns + ")"'/>
            <SetVar name="_indexname" value='#indexname.trim().equals("") ? "" : " " + #QB + #indexname + #QE'/>

            <Command>
               <SQL>
                  <![CDATA[create${_type} index${_indexname} on "${schema}"."${objectname}" ${_columns}]]>
               </SQL>
            </Command>
            <Confirm>
               <![CDATA[Create index "${indexname}"?]]>
            </Confirm>
            <Result>
               <![CDATA[Index "${indexname}" created!]]>
            </Result>
         </Action>

         <!-- TODO A WAY TO EITHER INSERT CODE or CLASS NAME -->
         <Action id="h2-tabletrigger-create" label="Create Trigger" icon="add" reload="true"
                 doclink="http://www.dbvis.com/doclink/create-trigger">
            <Input label="Schema" style="text" editable="false">
               <Default>${schema}</Default>
            </Input>
            <Input label="Trigger Name" name="triggerName" style="text"/>
            <Input label="Trigger BEFORE" name="triggerTime" style="radio">
